/**
*	SpinalJS | UI Module Package
*	@author Patricio Ferreira <3dimentionar@gmail.com>
**/
define(['ui/view',
		'ui/container',
		'ui/basic/paragraph',
		'ui/basic/link',
		'ui/basic/header',
		'ui/basic/label',
		'ui/basic/span',
		'ui/basic/image',
		'ui/misc/panel',
		'ui/misc/dropdown',
		'ui/misc/dialog',
		'ui/misc/autocomplete',
		'ui/misc/affix',
		'ui/list/list',
		'ui/list/list-item',
		'ui/table/table',
		'ui/table/table-element',
		'ui/form/form',
		'ui/form/mapper/form-mapper',
		'ui/form/controls/fieldset',
		'ui/form/controls/button',
		'ui/form/controls/input',
		'ui/form/controls/checkbox',
		'ui/form/controls/radio',
		'ui/form/controls/password',
		'ui/form/controls/hidden',
		'ui/form/controls/textarea',
		'ui/form/controls/select',
		'ui/form/controls/option'], function() { });
